version: '3.1'

services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=Example Inc.
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=admin
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap

volumes:
  ldap_data: